### ISSUE TITLE
Implement SSL support in Postgres connector config

### ISSUE THREAD

**Issue by marcinkoperski** [OS2iot/OS2IoT-backend#114]

**Comment by Joiversen** [comment]
Thank you for contributing @marcinkoperski. We appreciate it!

I have added your issue to OS2iot's backlog, from where it will be handled.

**Comment by MadsSvejstrup** [comment]
Hi @marcinkoperski

Can you please elaborate a bit on this request?

What use case are you envisioning and what connector config you are referring to?

**Comment by marcinkoperski** [comment]
@MadsSvejstrup Currently it's not possible to enable SSL on connection to Postgres:
https://github.com/OS2iot/OS2IoT-backend/blob/master/src/modules/app.module.ts#L43

**Comment by MadsSvejstrup** [comment]
Alright that makes sense, thank you!

We'll look into it.
