### ISSUE TITLE
Allow overriding 'admin' chirpstack user name by environmental variable

### ISSUE THREAD

**Issue by marcinkoperski** [OS2iot/OS2IoT-backend#116]
https://github.com/OS2iot/OS2IoT-backend/blob/4ba5cf46ba9f7115fb6213b5484cadaef4365d64/src/services/chirpstack/jwt-token.ts#L17

**Comment by Joiversen** [comment]
Hi @marcinkoperski,

Thanks for creating issues! 

I just added a new section to the documentation that might solve this: https://os2iot.readthedocs.io/en/latest/users-notes/users-notes.html#how-to-change-chirpstacks-admin-password

**Comment by ramogens** [comment]
Hi @marcinkoperski 
We've looked further into this and have initiated a fix that involves updating Chirpstack in the backend.

**Comment by ramogens** [comment]
Fix planned in January/February. Track progress in JIRA: https://os2web.atlassian.net/browse/IOT-1188

**Comment by ramogens** [comment]
Hi @marcinkoperski 
We're finally starting work on a fix but are unsure if this is still an issue. There is a suggestion for a solution at https://os2iot.readthedocs.io/en/latest/users-notes/users-notes.html#how-to-change-chirpstacks-admin-password that makes it possible to avoid the 'admin' user name.

Could you please add some more words on the problem and what you aim to achieve, if you need us to do any further?
Thanks!

**Comment by ramogens** [comment]
Hi @marcinkoperski 
Since I haven't heard from you, I presume the issue is no longer relevant, so I'm closing this issue.
