### ISSUE TITLE
Missing validation on 'type', when creating a new Iot-device

### ISSUE THREAD

**Issue by ellesgaard** [OS2iot/OS2IoT-backend#135]
Server returns 500 when creating an IoT-device without a type.
Response should be 400, with a validation error of missing/incorrect type.
As is done, if name is missing.

**Submitting w/o a type returns 500**
![500](https://user-images.githubusercontent.com/858486/149893842-fb4c7f20-9217-4d04-af15-fadd1854a32f.PNG)

**Submitting w/o a name returns 400**
![400](https://user-images.githubusercontent.com/858486/149893869-81dfda63-be21-40f3-a957-464f9df2d8d0.PNG)

**Check that server returns 201, when all three params is present**
![ok](https://user-images.githubusercontent.com/858486/149893877-9f497ede-df9b-45cb-97a1-b5a0c139c466.PNG)

**Comment by ramogens** [comment]
Thank you for pitching in and for thorough reporting @ellesgaard . We'll put the bug in the maintenance backlog.
