### ISSUE TITLE
Device-model id is not set on each iot-device in the API method GET: /api/v1/application/{id}/iot-devices

### ISSUE THREAD

**Issue by Bygdrift** [OS2iot/OS2IoT-backend#173]
When using the above mentioned call, I can read the `device-model name` attached to each iot-device, but  unfortunately not the `device-model id`, so I have to make a call to each iot-device with `GET /api/v1/iot-device/{id}`, to get the device-model id.
It would be nice if this information was added in the future.
Regards Kenneth

**Comment by ramogens** [comment]
Hi @Bygdrift 
Thank you for contributing to the improvement of OS2iot. I have added the issue to our Jira backlog: https://os2web.atlassian.net/browse/IOT-1346 
Best, Mogens

**Comment by ramogens** [comment]
Hi @Bygdrift 
With last week's release of version 1.4.0 the device-model id is now included.
Regards
Mogens
